language: go

go:
  - 1.10.x
  - 1.11.x

branches: # build only on these branches
  only:
    - master

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

notifications:
    webhooks: https://oapi.dingtalk.com/robot/send?access_token=096ed387df243a6d60835aadeccc47165f3813bc7cb81cdd0cfeadfd28e3acc1
    email: false
    on_success: change
    on_failure: always

script:
  - go vet ./sdk
  - go vet ./services/...
  - go build ./sdk
  - go build ./services/...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./sdk/...
  - if [ "$TRAVIS_BRANCH" == "master" ]; then go test -v -timeout 60s ./integration/... ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
